### ISSUE TITLE
An error accord

### ISSUE THREAD

**Issue by ghost** [gilmaimon/Discord-Movies-Bot#2]
sometimes it just says that but once I got this
`exception ignored in: <bound method DNSResolver.__del__ of <aiodns.DNSResolver object at 0x7f1dab509940>>
Traceback (most recent call last):
  File "/home/viknik/.local/lib/python3.6/site-packages/aiodns/__init__.py", line 148, in __del__
    self._channel.destroy()
AttributeError: 'Channel' object has no attribute 'destroy'
Exception ignored in: <bound method DNSResolver.__del__ of <aiodns.DNSResolver object at 0x7f1dab52a6d8>>
Traceback (most recent call last):
  File "/home/viknik/.local/lib/python3.6/site-packages/aiodns/__init__.py", line 148, in __del__
    self._channel.destroy()
`

**Comment by ghost** [comment]
I only get 2nd error once I shut down bot

**Comment by gilmaimon** [comment]
Hi @Nikita11790,

This project is not really maintained, so if you manage to solve the issue you could PR the fix.

I will probably not have the time to look into this issue, but if I will I'll post any progress here.

Gil.
